config/routes.rb
Rails.application.routes.draw do
  resources :scouting_entries do
    collection do
      post '/mass' => 'scouting_entries#mass'
    end
  end
  resources :divisions
  resources :team_stats
  root 'pages#home'

  resources :members do
    collection do
      post '/reject' => 'members#reject'
    end
    post '/approve'  => 'members#approve'
    resources :attendances
  end

  resources :posts, type: "Post"
  get '/blog', to: redirect('/posts')

  resources :events, only: [:new, :create, :edit, :update] do
    post '/reply' => 'events#reply', :constraints => {:format => :js}
  end

  resources :polls, only: [:new, :create, :edit, :update] do
    post '/vote' => 'polls#vote', :constraints => {:format => :js}
  end

  get '/events', to: redirect('/posts')
  get '/polls', to: redirect('/posts')

  resources :events, only: [:index, :destroy, :show], controller: :posts, type: "Event"
  resources :polls, only: [:index, :destroy, :show], controller: :posts, type: "Poll"

  resources :sponsors, except: [:show]

  #resources :photos, except: [:show]

  resources :videos, except: [:show]

  resources :teams

  post 'add_team_member' => 'teams#add_team_member'
  post 'remove_team_member' => 'teams#remove_team_member'

  resources :competitions

  scope :attendances do
    get 'center' => 'attendances#center', as: :attendances_center
    post 'check_in' => 'attendances#check_in'
    post 'set_check_in' => 'attendances#set_check_in'
    post 'check_out/:id' => 'attendances#check_out', as: :check_out
  end

  post '/checkout_all' => 'attendances#checkout_all'
  post '/checkin_group' => 'attendances#checkin_group'
  post '/checkout_group' => 'attendances#checkout_group'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  get 'forgot' => 'members#forgot'
  post 'forgot' => 'members#send_reset_token'

  get 'email' => 'members#edit_email'
  post 'email' => 'members#update_email'

  get 'password' => 'members#edit_password'
  post 'password' => 'members#update_password'

  get 'reset/:record_hex/:reset_token' => 'members#reset_password_edit', as: :reset_password, type: :reset
  post 'reset/:record_hex/:reset_token' => 'members#reset_password_update', type: :reset

  get '/set-password/:record_hex/:reset_token' => 'members#reset_password_edit', type: :set
  post '/set-password/:record_hex/:reset_token' => 'members#reset_password_update', type: :set

  get '/attend' => 'pages#attend'
  get '/event' => 'pages#event'
  get '/vex' => 'pages#vex'
  get '/skills' => 'pages#skills'
  get '/frc-ceta' => 'pages#other_competitions'
  get '/photos' => 'pages#photos'
  get '/mentors' => 'pages#mentors'
  get '/team-editor' => 'pages#team_editor'
  get '/about' => 'pages#about_us'
  get '/website' => 'pages#website'
  get '/myattendance' => 'pages#my_attendance'
  get '/contact' => 'pages#contact', :constraints => {:format => :html}
  post '/contact' => 'pages#contact_message', :constraints => {:format => :html}
  get '/search' => 'members#search'
  get '/eventsearch' => 'members#eventsearch'

  get  'dig' => 'pages#image_digest'
  post 'dig' => 'pages#image_digest'

  get '/register' => 'registrations#form'
  post '/register' => 'registrations#submit'
  get '/register/contract' => 'pages#member_contract'

  post 'registration/toggle' => 'registrations#toggle'

  resources :registration_fields, except: [:show] do
    collection do
      post '/fix' => 'registration_fields#fix'
    end
    post '/up' => 'registration_fields#up'
    post '/down' => 'registration_fields#down'
  end

  mount_griddler('/email/3E9A2CE')
end

app/models/registration_field.rb
class RegistrationField < ApplicationRecord
  enum input_type: [:text_field, :text_area, :select_tag]
  serialize :extra_info

  before_create :set_order
  before_destroy :correct_fields_order

  before_validation :try_map_to_member
  after_commit :verify_registration_fields

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validate :select_tag_extra_info, if: :select_tag?
  validate :uniq_map_to

  def self.cache_key
    [count(:updated_at),maximum(:updated_at)].map(&:to_i).join('-')
  end

  def extra_info_for_human
    if input_type == "select_tag" && !extra_info.blank?
      if extra_info.length <= 1
        extra_info[0]
      else
        "#{extra_info[0...(-1)].join(',')} or #{extra_info[-1]}"
      end
    end
  end

  def self.input_type_for_select
    {
      "Text Field (Short Text or Number)" => :text_field,
      "Text Area (Long Paragraph)" => :text_area,
      "Select Tag (Single Choice Options)" => :select_tag
    }
  end

  def options
    if @options.present?
      @options
    elsif input_type == "select_tag"
      @options = extra_info.join("\n")
    else
      nil
    end
  end

  def options=(val)
    @options = val
    unless @options.nil?
      if input_type == "select_tag"
        self.extra_info = @options.lines.map(&:chomp)
      end
    end
  end

  def try_map_to_member
    return unless title_changed?
    title_underscore = title.to_s.downcase.parameterize.underscore
    if title_underscore == 'e_mail' #Force covert e-mail to email to ensure consistency
      self.title = 'Email'
      title_underscore = 'email'
    end
    if mappable_attribute =  Member.mappable_attributes[title_underscore]
      self.map_to = title_underscore
      self.input_type = mappable_attribute[:type]
      self.extra_info = mappable_attribute[:extra_info]
      unless mappable_attribute[:optional].nil?
        self.optional = mappable_attribute[:optional]
      end
    end
    true
  end

  def self.valid_member_fields?
    where(map_to: [:first_name, :last_name, :email, :grade, :student_number]).count == 5
  end

  def input_value_valid?(value)
    if value.blank?
      self.optional
    elsif select_tag?
      self.extra_info.include?(value.to_s)
    else
      true
    end
  end

  private
  def set_order
    self.order = RegistrationField.all.count
  end

  def correct_fields_order
    RegistrationField.where("\"registration_fields\".\"order\" > #{self.order}").update_all("\"order\" = \"order\" - 1")
  end

  def select_tag_extra_info
    errors.add(:options, 'should have at least 2 lines') if (self.extra_info.nil? || self.extra_info.length < 2)
  end

  def uniq_map_to
    unless map_to.nil? || errors[:title].any? || !map_to_changed?
      flag = false
      if new_record?
        flag = RegistrationField.where(map_to: map_to).exists?
      else
        flag = RegistrationField.where(map_to: map_to).where.not(id: self.id).exists?
      end
      errors.add(:base, "Map to attribute value has already taken. This error may causes by similar title with another field") if flag
    end
  end

  def verify_registration_fields
    valid_fields = GlobalVar[:valid_registration_fields] = RegistrationField.valid_member_fields?
    RegistrationForm.verify_registration_fields!(valid_fields)
  end
end

app/controllers/registration_fields_controller.rb
class RegistrationFieldsController < ApplicationController
  before_action :set_registration_field, only: [:edit, :update, :destroy, :up, :down]

  def index
  end

  def new
    @registration_field = RegistrationField.new
  end

  def edit
  end

  def create
    @registration_field = RegistrationField.new(registration_field_params)
    respond_to do |format|
      if @registration_field.save
        format.html { redirect_to registration_fields_url, notice: 'Registration field was successfully created.' }
        format.json { render :show, status: :created, location: @registration_field }
      else
        format.html { render :new }
        format.json { render json: @registration_field.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @registration_field.update(registration_field_params)
        format.html { redirect_to registration_fields_url, notice: 'Registration field was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_field }
      else
        format.html { render :edit }
        format.json { render json: @registration_field.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @registration_field.destroy
    respond_to do |format|
      format.html { redirect_to registration_fields_url, notice: 'Registration field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fix
    RegistrationField.create([{ title: "First name" }, { title: "Last name" }, { title: "Email" }, { title: "Grade" }, { title: "Student number" }])
    respond_to do |format|
      format.html { try_redirect_back { redirect_to registration_fields_url, notice: 'Registration fields\' issues were successfully fixed.' } }
    end
  end

  def up
    unless @registration_field.order == 0
      @swap_field = RegistrationField.find_by(order: @registration_field.order - 1)
      @swap_field.order += 1
      @swap_field.save
      @registration_field.order -= 1
      @registration_field.save
    end
    respond_to do |format|
      format.html { redirect_to registration_fields_url }
      format.json { head :no_content }
      format.js { render :update_rows }
    end
  end

  def down
    unless @registration_field.order == (RegistrationField.count - 1)
      @swap_field = RegistrationField.find_by(order: @registration_field.order + 1)
      @swap_field.order -= 1
      @swap_field.save
      @registration_field.order += 1
      @registration_field.save
    end
    respond_to do |format|
      format.html { redirect_to registration_fields_url }
      format.json { head :no_content }
      format.js {render :update_rows}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_field
      @registration_field = RegistrationField.find(params[:registration_field_id] || params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_field_params
      params.require(:registration_field).permit(:title, :input_type, :options, :optional)
    end
end

app/helpers/registration_fields_helper.rb
module RegistrationFieldsHelper
end

app/views/registration_fields/_field_rows.html.erb
<% RegistrationField.order(order: :ASC, id: :ASC).each do |field| %>
<% cache(field) do %>
<tr>
  <td><%= field.order + 1 %></td>
  <td><%= field.title %></td>
  <td><%= field.input_type.titleize %><%= " (#{field.extra_info_for_human})" if field.extra_info.present? %></td>
  <td><%= field.optional ? 'optional' : '✓' %></td>
  <td><%= link_to 'Up', registration_field_up_path(field), method: :post, remote: true, data: { disable_with: nil } %></td>
  <td><%= link_to 'Down', registration_field_down_path(field), method: :post, remote: true, data: { disable_with: nil } %></td>
  <td><%= link_to 'Edit', edit_registration_field_path(field) %></td>
  <td><%= link_to 'Delete', field, method: :delete, data: { disable_with: nil, confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
<% end %>

app/views/registration_fields/_form.html.erb
<%= form_for(@registration_field) do |f| %>
  <%= errors_for @registration_field %>

  <div class="row large-margin-bottom">
    <div class="input-field col s12 m12 l12">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="input-field col s12 m8 l6">
      <%= f.select :input_type, RegistrationField.input_type_for_select %>
      <%= f.label :input_type %>
    </div>
    <div class="input-field col s12 m4 l4 check-box-field">
      <%= f.check_box :optional %>
      <%= f.label :optional %>
    </div>
    <div class="input-field col s12">
      <%= f.text_area :options, class: "materialize-textarea" %>
      <%= f.label :options, 'Select Tag Options' %>
    </div>
  </div>

  <div class="row">
    <div class="actions col s12">
      <%= f.submit class: 'btn', data: { disable_with: nil } %>
      <%= link_to 'Back', posts_path, class: 'btn-flat' %>
    </div>
  </div>
<% end %>

app/views/registration_fields/_table.html.erb
<div id="registration_fields_table_wrapper">
<h3 class="flow-text">Registration Form Fields</h3>
<div id="registration_fields_table" class="card-panel" style="padding:10px;">
  <table class="flow-text centered bordered except-last responsive-table" style="font-size:100%;">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th><span class="hide-on-small-only">Input </span>Type</th>
        <th>Required</th>
        <th class="hide-on-med-and-down" colspan="4">Actions</th>
        <th class="hide-on-large-only"></th>
        <th class="hide-on-large-only"></th>
        <th class="hide-on-large-only"></th>
        <th class="hide-on-large-only"></th>
      </tr>
    </thead>
    <tbody>
      <%= render 'registration_fields/field_rows' %>
    </tbody>
  </table>
  <div class="center-align hide-on-large-only">
    <br>
    <%= link_to 'New Registration Field', new_registration_field_path %>
    <br><br>
    <% if RegistrationField.valid_member_fields? %>
    <%= link_to r_url, r_url %> or <%= link_to register_url, register_url %>
    <% else %>
    Invalid form: Require first name, last name, email, and grade fields <%= link_to 'Quick FIX', fix_registration_fields_path, method: :post, remote: true, data: { disable_with: nil } %>
    <% end %>
  </div>
</div>
</div>

app/views/registration_fields/edit.html.erb
<h1 class="flow-text">Editing Registration Field</h1>

<div class="card-panel" style="padding-bottom:15px;padding-top:10px;">
<%= render 'form' %>
</div>

app/views/registration_fields/index.html.erb
<h3 class="flow-text">Registration Form Fields</h3>
<div id="registration_fields_table" class="card-panel" style="padding:10px;">
  <table class="flow-text centered bordered responsive-table" style="font-size:100%;">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th><span class="hide-on-small-only">Input </span>Type</th>
        <th>Required</th>
        <th class="hide-on-med-and-down" colspan="4">Actions</th>
        <th class="hide-on-large-only"></th>
        <th class="hide-on-large-only"></th>
        <th class="hide-on-large-only"></th>
        <th class="hide-on-large-only"></th>
      </tr>
    </thead>
    <tbody>
      <%= render 'registration_fields/field_rows' %>
    </tbody>
  </table>
  <div class="center-align" style="margin-top:30px;">
    <%= link_to 'New Registration Field', new_registration_field_path, class: 'btn' %><br>
    <%= link_to 'Back To Members Center', members_path, class: 'btn-flat' %>
  </div>
</div>

app/views/registration_fields/new.html.erb
<h1 class="flow-text">New Registration Field</h1>

<div class="card-panel" style="padding-bottom:15px;padding-top:10px;">
<%= render 'form' %>
</div>

app/views/registration_fields/update_rows.js.erb
$('#registration_fields_table tbody').first().html('<%= escape_javascript render("registration_fields/field_rows") %>');