config/routes.rb
Rails.application.routes.draw do
  resources :scouting_entries do
    collection do
      post '/mass' => 'scouting_entries#mass'
    end
  end
  resources :divisions
  resources :team_stats
  root 'pages#home'

  resources :members do
    collection do
      post '/reject' => 'members#reject'
    end
    post '/approve'  => 'members#approve'
    resources :attendances
  end

  resources :posts, type: "Post"
  get '/blog', to: redirect('/posts')

  resources :events, only: [:new, :create, :edit, :update] do
    post '/reply' => 'events#reply', :constraints => {:format => :js}
  end

  resources :polls, only: [:new, :create, :edit, :update] do
    post '/vote' => 'polls#vote', :constraints => {:format => :js}
  end

  get '/events', to: redirect('/posts')
  get '/polls', to: redirect('/posts')

  resources :events, only: [:index, :destroy, :show], controller: :posts, type: "Event"
  resources :polls, only: [:index, :destroy, :show], controller: :posts, type: "Poll"

  resources :sponsors, except: [:show]

  #resources :photos, except: [:show]

  resources :videos, except: [:show]

  resources :teams

  post 'add_team_member' => 'teams#add_team_member'
  post 'remove_team_member' => 'teams#remove_team_member'

  resources :competitions

  scope :attendances do
    get 'center' => 'attendances#center', as: :attendances_center
    post 'check_in' => 'attendances#check_in'
    post 'set_check_in' => 'attendances#set_check_in'
    post 'check_out/:id' => 'attendances#check_out', as: :check_out
  end

  post '/checkout_all' => 'attendances#checkout_all'
  post '/checkin_group' => 'attendances#checkin_group'
  post '/checkout_group' => 'attendances#checkout_group'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  get 'forgot' => 'members#forgot'
  post 'forgot' => 'members#send_reset_token'

  get 'email' => 'members#edit_email'
  post 'email' => 'members#update_email'

  get 'password' => 'members#edit_password'
  post 'password' => 'members#update_password'

  get 'reset/:record_hex/:reset_token' => 'members#reset_password_edit', as: :reset_password, type: :reset
  post 'reset/:record_hex/:reset_token' => 'members#reset_password_update', type: :reset

  get '/set-password/:record_hex/:reset_token' => 'members#reset_password_edit', type: :set
  post '/set-password/:record_hex/:reset_token' => 'members#reset_password_update', type: :set

  get '/attend' => 'pages#attend'
  get '/event' => 'pages#event'
  get '/vex' => 'pages#vex'
  get '/skills' => 'pages#skills'
  get '/frc-ceta' => 'pages#other_competitions'
  get '/photos' => 'pages#photos'
  get '/mentors' => 'pages#mentors'
  get '/team-editor' => 'pages#team_editor'
  get '/about' => 'pages#about_us'
  get '/website' => 'pages#website'
  get '/myattendance' => 'pages#my_attendance'
  get '/contact' => 'pages#contact', :constraints => {:format => :html}
  post '/contact' => 'pages#contact_message', :constraints => {:format => :html}
  get '/search' => 'members#search'
  get '/eventsearch' => 'members#eventsearch'

  get  'dig' => 'pages#image_digest'
  post 'dig' => 'pages#image_digest'

  get '/register' => 'registrations#form'
  post '/register' => 'registrations#submit'
  get '/register/contract' => 'pages#member_contract'

  post 'registration/toggle' => 'registrations#toggle'

  resources :registration_fields, except: [:show] do
    collection do
      post '/fix' => 'registration_fields#fix'
    end
    post '/up' => 'registration_fields#up'
    post '/down' => 'registration_fields#down'
  end

  mount_griddler('/email/3E9A2CE')
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "Member", :foreign_key => "author_id"
  has_and_belongs_to_many :teams

  enum restriction: [:everyone, :member, :limited, :admin]

  validates :restriction, presence: true

  validates :title, presence: true
  validates :description, presence: true
  validates :description_stripdown, length: { maximum: 250 }

  before_save :remove_useless_limited_teams
  before_save :process_description

  def self.valid_restrictions
    restrictions
  end

  def email_notification
    @email_notification ||= false
  end

  def email_notification=(val)
    if val.is_a? String
      val = (val =~ (/^(true|t|yes|y|1)$/i)) ? true : false
    else
      val = (val == true)
    end
    @email_notification = val
  end

  def add_limited_teams(teams)
    teams.each do |t|
      if team = Team.find_by(id: t.to_i)
        self.teams << team
      end
    end
  end

  def audience_description
    case self.restriction
    when "everyone"
      self.restriction.capitalize
    when "limited"
      teams_description = self.teams.all.order(:name).pluck(:name).join(', ')
      teams_description = "Limited (ADMIN ONLY)" if teams_description.blank?
      teams_description
    else
      self.restriction.pluralize.capitalize
    end
  end

  def process_description(force = false)
    if self.description_changed? || force
      self.description_markdown = MarkdownRender.render(self.description)
      self.description_stripdown = MarkdownRender.stripdown(self.description.truncate(240)).truncate(250, omission: '')
    end
  end

  private
  def remove_useless_limited_teams
    if self.restriction_changed? && self.restriction_was == "limited"
      self.teams.clear
    end
    true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_admin!, only: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @page_title = member_signed_in? ? "Posts" : "Blog"
    set_meta_tags canonical: "https://4659warriors.com/posts"
    case params[:type]
    when "Event"
      post_scope = Event
    when "Poll"
      post_scope = Poll
    else
      post_scope = Post
    end
    if member_signed_in?
      if current_member.team_id.nil? || member_is_admin?
        post_scope = post_scope.where('"posts"."restriction" <= ?', max_restriction)
      else
        post_scope = post_scope.joins('LEFT JOIN "posts_teams" ON "posts_teams"."post_id" = "posts"."id"').where('"posts"."restriction" <= ? OR "posts_teams"."team_id" = ?', max_restriction, current_member.team_id)
      end
    else
      post_scope = post_scope.where(restriction: 0)
    end
    @posts = post_scope.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if @post[:restriction] > max_restriction
      if member_signed_in?
        unless @post.team_ids.include?(current_member.team_id)
          raise Forbidden
        end
      else
        redirect_to signin_path(return_to_info)
      end
    end

    @page_title = @post.title
    set_meta_tags description: @post.description_stripdown, canonical: "https://4659warriors.com/posts/#{@post.id}"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post=  Post.new(post_params)
    @post.author = current_member
    if @post.limited? && params[:teams].present?
      @post.team_ids = params[:teams].keys
    end

    respond_to do |format|
      if @post.save
        if @post.email_notification
          PostMailer.post_email(@post, true).deliver_later
        end
        format.html { try_redirect_back { redirect_to @post, notice: 'Post was successfully created.' } }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if (params[:post][:restriction] == "limited" || (params[:post][:restriction].nil? && @post.limited?)) && params[:teams].present?
        @post.team_ids = params[:teams].keys
      end
      if @post.update(post_params)
        if @post.email_notification
          PostMailer.post_email(@post, false).deliver_later
        end
        format.html { try_redirect_back { redirect_to @post, notice: 'Post was successfully updated.' } }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :restriction, :email_notification, :disabled)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_compact_form.html.erb
<div id="post_form_wrap" class="col s12  compact-form-wrap">
  <%= form_for(post) do |f| %>
    <%= hidden_field_tag :from, from if local_assigns[:from].present? %>
    <%= render "compact_post_fields", f: f %>
    <div>
      <%= f.submit class: 'btn right', data: { disable_with: nil } %>
    </div>
  <% end %>
</div>

app/views/posts/_compact_post_fields.html.erb
<div class="row">
  <div class="input-field col s12 m9">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="input-field col s12 m3 post-restriction">
    <%= f.select :restriction, f.object.class.valid_restrictions.map { |k,v| [k.capitalize, k] }, {} %>
    <%= f.label :restriction %>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <%= f.text_area :description, class: "materialize-textarea" %>
    <%= f.label :description %>
  </div>
</div>
<div class="row sp-post-f-row post-limited-teams"<%= raw(" style=\"display:none\"") unless (f.object.restriction == 'limited') %>>
  <% teams = f.object.persisted? ? f.object.team_ids : []  %>
  <% Team.all.order(name: :ASC).each do |team| %>
  <div class="input-field col s3 x-large-margin-bottom">
    <%= check_box_tag "teams[#{team.id}]", '1', (params[:teams].try('[]',team.id.to_s) == '1' || (params[:team].nil? && teams.include?(team.id))) %>
    <%= label_tag "teams[#{team.id}]", team.name %>
  </div>
  <% end %>
</div>
<div class="row sp-post-f-row">
  <div class="input-field col s6 m4">
    <%= f.check_box :email_notification %>
    <%= f.label :email_notification %>
  </div>
  <div class="input-field col s6 m3 l3">
    <%= f.check_box :disabled %>
    <%= f.label :disabled %>
  </div>
  <div class="col s12 m5 right-align hide-on-small-only">
    <%= link_to('https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet', class: "note") do %>
    Support markdown<span class="hide-on-med-and-down"> ( images, links, etc )</span>
    <% end %>
  </div>
</div>

app/views/posts/_event_reply.html.erb
<%= form_tag event_reply_path(post), remote: true  do %>
<% reply = post.reply_from(current_member) %>
<table class="unselectable" data-row-trigger-input>
<% ({'yes' => 'confirmed', 'maybe' => 'maybe', 'no' => 'declined' }).each do |key, value| %>
  <tr>
    <td><%= radio_button_tag 'reply', value, reply == value, class: "stop-propagation", data: {"trigger-form" => "1"} %></td>
    <td><%= label_tag "reply_#{value}", key.capitalize %></td>
    <td><%= post.replyers_description(value) %></td>
  </tr>
<% end %>
</table>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= errors_for f.object %>
  
  <%= hidden_field_tag :from, params[:from] if params[:from].present? %>
  <%= render partial: "posts/post_fields", locals: {f: f} %>
  <div class="row">
    <div class="actions col s12">
      <%= f.submit class: 'btn', data: { disable_with: nil } %>
      <%= link_to 'Back', posts_path, class: 'btn-flat' %>
    </div>
  </div>
<% end %>

app/views/posts/_index_create.html.erb
<div class="card-panel max8 hide-on-small-only quick-create">
  <div class="row no-margin-bottom">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a class="active" href="#post_form_wrap"><i class="tiny material-icons">chat_bubble_outline</i>Post</a></li>
        <li class="tab col s3"><a href="#event_form_wrap"><i class="tiny material-icons">today</i>Event</a></li>
        <li class="tab col s3"><a href="#poll_form_wrap"><i class="tiny material-icons">equalizer</i>Poll</a></li>
      </ul>
    </div>
    <%= render "posts/compact_form", post: Post.new, from: request_path %>
    <%= render "events/compact_form", event: Event.new, from: request_path %>
    <%= render "polls/compact_form", poll: Poll.new, from: request_path %>
  </div>
  <div class="preloader-container">
    <%= render "components/spinner", color: "yellow" %>
  </div>
</div>
<div class="quick-links card-panel hide-on-med-and-up max8">
  <div class="row">
    <%= link_to new_post_path, class: "btn col s12" do %>
    <i class="material-icons left">chat_bubble_outline</i>Create Post
    <% end %>
    <%= link_to new_event_path, class: "btn col s12" do %>
    <i class="material-icons left">today</i>Create Event
    <% end %>
    <%= link_to new_poll_path, class: "btn col s12" do %>
    <i class="material-icons left">equalizer</i>Create Poll
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<% cache([post, member_is_admin?]) do %>
<%= render layout: 'post_wrap', locals: {post: post} do %>
<% end %>
<% end %>

app/views/posts/_post_fields.html.erb
<% if f.object.author.present? %>
<div class="field grey-text">
  Original Author:
  <%= f.object.author.full_name %>
</div>
<br>
<% end %>
<%= render 'posts/compact_post_fields', f: f %>

app/views/posts/_post_wrap.html.erb
<div class="post-box" id="post<%= post.id %>">
  <div class="heading">
    <span class="title"><%= link_to "#{post.title}", post %></span>
    <div style="float:right;margin-top:2%;">
      <% if member_is_admin? %>
      <%= link_to 'create', send("edit_#{post.model_name.element}_path",post, from: request_path), class: "material-icons" %>
      <%= link_to 'delete', post, class: "material-icons", method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>

  <div class="flow-text body markdown"><%= raw(post.description_markdown) %></div>

  <%= yield %>

  <div class="right-align info">
    <%= "Disabled - " if post.disabled %><%= post.created_at.strftime("%A, %B %e, %Y @ %l:%M %p") %> - <%= post.author.try(:abbr_name) %> to <%= post.audience_description %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="flow-text">Editing Post</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% if member_is_admin? && (params[:page].nil? || params[:page] == "1") %>
<% cache do %>
<%= render(partial: "index_create")  %>
<% end %>
<% end %>
<div class="posts-container">
<% @posts.each do |post| %>
  <%= render post %>
<% end %>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1 class="flow-text">New Post</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="posts-container card-panel">
  <%= render @post %>
</div>
<p class="center-align">
  <br>
  <a href="/posts"> Show All Posts </a>
</p>
<% if member_is_admin? && @post.type == "Poll" %>
  <% cache(['voter_list',@post]) do %>
  <%= render 'polls/voter_list', poll: @post %>
  <% end %>
<% end %>