config/routes.rb
Rails.application.routes.draw do
  resources :scouting_entries do
    collection do
      post '/mass' => 'scouting_entries#mass'
    end
  end
  resources :divisions
  resources :team_stats
  root 'pages#home'

  resources :members do
    collection do
      post '/reject' => 'members#reject'
    end
    post '/approve'  => 'members#approve'
    resources :attendances
  end

  resources :posts, type: "Post"
  get '/blog', to: redirect('/posts')

  resources :events, only: [:new, :create, :edit, :update] do
    post '/reply' => 'events#reply', :constraints => {:format => :js}
  end

  resources :polls, only: [:new, :create, :edit, :update] do
    post '/vote' => 'polls#vote', :constraints => {:format => :js}
  end

  get '/events', to: redirect('/posts')
  get '/polls', to: redirect('/posts')

  resources :events, only: [:index, :destroy, :show], controller: :posts, type: "Event"
  resources :polls, only: [:index, :destroy, :show], controller: :posts, type: "Poll"

  resources :sponsors, except: [:show]

  #resources :photos, except: [:show]

  resources :videos, except: [:show]

  resources :teams

  post 'add_team_member' => 'teams#add_team_member'
  post 'remove_team_member' => 'teams#remove_team_member'

  resources :competitions

  scope :attendances do
    get 'center' => 'attendances#center', as: :attendances_center
    post 'check_in' => 'attendances#check_in'
    post 'set_check_in' => 'attendances#set_check_in'
    post 'check_out/:id' => 'attendances#check_out', as: :check_out
  end

  post '/checkout_all' => 'attendances#checkout_all'
  post '/checkin_group' => 'attendances#checkin_group'
  post '/checkout_group' => 'attendances#checkout_group'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  get 'forgot' => 'members#forgot'
  post 'forgot' => 'members#send_reset_token'

  get 'email' => 'members#edit_email'
  post 'email' => 'members#update_email'

  get 'password' => 'members#edit_password'
  post 'password' => 'members#update_password'

  get 'reset/:record_hex/:reset_token' => 'members#reset_password_edit', as: :reset_password, type: :reset
  post 'reset/:record_hex/:reset_token' => 'members#reset_password_update', type: :reset

  get '/set-password/:record_hex/:reset_token' => 'members#reset_password_edit', type: :set
  post '/set-password/:record_hex/:reset_token' => 'members#reset_password_update', type: :set

  get '/attend' => 'pages#attend'
  get '/event' => 'pages#event'
  get '/vex' => 'pages#vex'
  get '/skills' => 'pages#skills'
  get '/frc-ceta' => 'pages#other_competitions'
  get '/photos' => 'pages#photos'
  get '/mentors' => 'pages#mentors'
  get '/team-editor' => 'pages#team_editor'
  get '/about' => 'pages#about_us'
  get '/website' => 'pages#website'
  get '/myattendance' => 'pages#my_attendance'
  get '/contact' => 'pages#contact', :constraints => {:format => :html}
  post '/contact' => 'pages#contact_message', :constraints => {:format => :html}
  get '/search' => 'members#search'
  get '/eventsearch' => 'members#eventsearch'

  get  'dig' => 'pages#image_digest'
  post 'dig' => 'pages#image_digest'

  get '/register' => 'registrations#form'
  post '/register' => 'registrations#submit'
  get '/register/contract' => 'pages#member_contract'

  post 'registration/toggle' => 'registrations#toggle'

  resources :registration_fields, except: [:show] do
    collection do
      post '/fix' => 'registration_fields#fix'
    end
    post '/up' => 'registration_fields#up'
    post '/down' => 'registration_fields#down'
  end

  mount_griddler('/email/3E9A2CE')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <%= display_meta_tags site: '4659 Warrior Robotix', separator: ' - ', reverse: true %>
  <meta name="google-site-verification" content="qqi6OdQ6UYhS4BlwnOuNhxK-ogqycLqHT4vgEGSi85I" />
  <link rel="apple-touch-icon" sizes="57x57" href="/icons/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/icons/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/icons/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/icons/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/icons/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/icons/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/icons/apple-icon-144x144.png">
  <link rel="icon" type="image/png" sizes="64x64"  href="/icons/icon-64x64.png">
  <link rel="icon" type="image/png" sizes="128x128"  href="/icons/icon-128x128.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/icons/icon-192x192.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>-<%= action_name %>">
<% cache(['navbar', (member_signed_in? ? current_member : 'visitor')]) do %>
<%= render 'components/navbar' %>
<% end %>
<main>
  <%= yield :above_container %>
  <div class="container">
  <%= yield %>
  </div>
</main>
<% cache do %>
<%= render 'components/footer' %>
<% end %>
<%= render 'components/side_buttons' if @show_side_buttons %>
<script type="text/javascript" data-turbolinks-eval=always>
  <%= raw(flash_toasts) %>
</script>
</body>
</html>

app/views/layouts/navbar.html.erb
<nav>
  <span>
  <%= link_to "WarriorRobotix", root_path %>
  <%= white_spaces(4) %>
  </span>
  <span style="float:right;">
  <%= link_to "Posts", posts_path %>
  <%= white_spaces(2) %>
  <%= link_to "Members", members_path %>
  <%= white_spaces(4) %>
<% if member_signed_in? %>
  Hi, <%= current_member.first_name %> <%= current_member.last_name %> <%= "(admin)" if member_is_admin? %> <%= link_to "Sign out", signout_path(return_to_info), method: :delete %>
<% else %>
  <%= link_to "Sign in", signin_path(return_to_info) %>
<% end %>
</span>
</nav>