config/routes.rb
Rails.application.routes.draw do
  resources :scouting_entries do
    collection do
      post '/mass' => 'scouting_entries#mass'
    end
  end
  resources :divisions
  resources :team_stats
  root 'pages#home'

  resources :members do
    collection do
      post '/reject' => 'members#reject'
    end
    post '/approve'  => 'members#approve'
    resources :attendances
  end

  resources :posts, type: "Post"
  get '/blog', to: redirect('/posts')

  resources :events, only: [:new, :create, :edit, :update] do
    post '/reply' => 'events#reply', :constraints => {:format => :js}
  end

  resources :polls, only: [:new, :create, :edit, :update] do
    post '/vote' => 'polls#vote', :constraints => {:format => :js}
  end

  get '/events', to: redirect('/posts')
  get '/polls', to: redirect('/posts')

  resources :events, only: [:index, :destroy, :show], controller: :posts, type: "Event"
  resources :polls, only: [:index, :destroy, :show], controller: :posts, type: "Poll"

  resources :sponsors, except: [:show]

  #resources :photos, except: [:show]

  resources :videos, except: [:show]

  resources :teams

  post 'add_team_member' => 'teams#add_team_member'
  post 'remove_team_member' => 'teams#remove_team_member'

  resources :competitions

  scope :attendances do
    get 'center' => 'attendances#center', as: :attendances_center
    post 'check_in' => 'attendances#check_in'
    post 'set_check_in' => 'attendances#set_check_in'
    post 'check_out/:id' => 'attendances#check_out', as: :check_out
  end

  post '/checkout_all' => 'attendances#checkout_all'
  post '/checkin_group' => 'attendances#checkin_group'
  post '/checkout_group' => 'attendances#checkout_group'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  get 'forgot' => 'members#forgot'
  post 'forgot' => 'members#send_reset_token'

  get 'email' => 'members#edit_email'
  post 'email' => 'members#update_email'

  get 'password' => 'members#edit_password'
  post 'password' => 'members#update_password'

  get 'reset/:record_hex/:reset_token' => 'members#reset_password_edit', as: :reset_password, type: :reset
  post 'reset/:record_hex/:reset_token' => 'members#reset_password_update', type: :reset

  get '/set-password/:record_hex/:reset_token' => 'members#reset_password_edit', type: :set
  post '/set-password/:record_hex/:reset_token' => 'members#reset_password_update', type: :set

  get '/attend' => 'pages#attend'
  get '/event' => 'pages#event'
  get '/vex' => 'pages#vex'
  get '/skills' => 'pages#skills'
  get '/frc-ceta' => 'pages#other_competitions'
  get '/photos' => 'pages#photos'
  get '/mentors' => 'pages#mentors'
  get '/team-editor' => 'pages#team_editor'
  get '/about' => 'pages#about_us'
  get '/website' => 'pages#website'
  get '/myattendance' => 'pages#my_attendance'
  get '/contact' => 'pages#contact', :constraints => {:format => :html}
  post '/contact' => 'pages#contact_message', :constraints => {:format => :html}
  get '/search' => 'members#search'
  get '/eventsearch' => 'members#eventsearch'

  get  'dig' => 'pages#image_digest'
  post 'dig' => 'pages#image_digest'

  get '/register' => 'registrations#form'
  post '/register' => 'registrations#submit'
  get '/register/contract' => 'pages#member_contract'

  post 'registration/toggle' => 'registrations#toggle'

  resources :registration_fields, except: [:show] do
    collection do
      post '/fix' => 'registration_fields#fix'
    end
    post '/up' => 'registration_fields#up'
    post '/down' => 'registration_fields#down'
  end

  mount_griddler('/email/3E9A2CE')
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy, :approve]

  skip_before_action :authenticate_admin!, only: [:index, :forgot, :send_reset_token, :reset_password_edit, :reset_password_update, :edit_email, :update_email, :edit_password, :update_password, :search]

  before_action :authenticate_member!, only: [:index, :edit_email, :update_email, :edit_password, :update_password]

  # GET /members
  # GET /members.json
  def index
    if params[:format] == "xlsx"
      authenticate_admin!
    end

    @current_members = Member.where(graduated_year: nil).order(team_id: :ASC,first_name: :ASC, last_name: :ASC).all
    if member_is_admin?
      @pending_members = Member.unscoped.where(accepted: false).all
      @graduated_members = Member.unscoped.where.not(graduated_year: nil).order(graduated_year: :DESC, first_name: :ASC, last_name: :ASC).all
    end
    @show_attend = (params[:show] == "attend") && member_is_admin?
    if @show_attend
      today = Time.zone.now
      @this_month_attendances = Attendance.where(status: 2, start_at: today.beginning_of_month..today).group(:member_id).all.count
      last_month = today.last_month
      @last_month_attendances = Attendance.where(status: 2, start_at: last_month.beginning_of_month..last_month.end_of_month).group(:member_id).all.count
    end
  end

  def eventsearch
    @student_number = params[:text]
    @member = Member.find_by(:student_number => @student_number)
    @event = Event.find(params[:id])
    @event_attendance_created = false
    @status = ""
    if !@member.nil?
      @member.attendances.each do |f|
        if !f.event_id.nil? && f.event_id == @event.id
          @event_attendance_created = true
          @event_attendance = f
        end
      end
      if @event_attendance_created == true
        if !@event_attendance.start_at.nil?
          if !@event_attendance.end_at.nil?
            #already signed in and out
            flash[:alert] = "Already Checked In and Out!"
          else
            #need to check out
            @event_attendance.update_attribute(:end_at, Time.zone.now)
            @event_attendance.update_attribute(:status, :attended)
            flash[:notice] = "Successfully Checked Out!"
          end
        else
          #need to check in
          @event_attendance.update_attribute(:start_at, Time.zone.now)
          @event_attendance.update_attribute(:status, :attending)
          flash[:notice] = "Successfully Checked In!"
        end
      else
        #need to create a new attendance and check in
        Attendance.create(:member_id => @member.id, :event_id => @event.id, :start_at => Time.zone.now, :status => :attending)
        flash[:notice] = "Successfully Checked In!"
      end
      redirect_to :back
    else
      #student number invalid
      redirect_to :back
      flash[:alert] = "Can not find anyone with that Student Number!"
    end
  end

  def search
    @student_number = params[:text]
    @member = Member.find_by(:student_number => @student_number)
    #Check if user is already checked-in
    @checked = false
    @checkedin_today = false
    success = false

    allow_checkin = true
    allow_checkout = true

    if params[:check] == 'in'
      allow_checkout = false
    elsif params[:check] == 'out'
      allow_checkin = false
    end

    if is_member_admin?
      is_from_admin = true
    elsif member_signed_in?
      is_from_admin = false
    else
      if admin = Member.find_by(admin: true, student_number: params[:identifier]).try(:authenticate, params[:password])
        is_from_admin = true
      else
        is_from_admin = false
      end
    end

    if !@member.nil? && is_from_admin
      @member.attendances.each do |f|
        if !f.start_at.nil? && f.status != :invited && f.event_id.nil?
          attendance_date = f.start_at.to_datetime
          current_date = Time.zone.now
          if attendance_date.day == current_date.day && attendance_date.month == current_date.month && attendance_date.year == current_date.year
            @checkedin_today = true
          end
          if f.end_at.nil? && @checkedin_today == true && allow_checkout == true
            f.update_attribute(:end_at, Time.zone.now)
            f.update_attribute(:status, :attended)
            @checked = true
            success = true
            flash[:notice] = "#{@member.full_name} has been checked out..."
          end
        end
      end
      if @checked == false && allow_checkin == true
        if @checkedin_today == false
          @attendance = Attendance.create(:member_id => @member.id, :start_at => Time.zone.now, :status => :attending)
          success = true
          flash[:notice] = "#{@member.full_name} has been checked in..."
        else
          flash[:alert] = "#{@member.full_name} has already checked in and out today!"
        end
      end
    else
      flash[:alert] = "Can not find anyone with that Student Number!"
    end
    respond_to do |format|
      format.html { redirect_to attend_path }
      format.json { render json: {success: success} }
    end
  end

  # GET /members/1
  # GET /members/1.json
  # GET /members/1.js
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to members_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        Rails.cache.delete("member/id/#{@member.id}")
        format.html { redirect_to members_path, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    Rails.cache.delete("member/id/#{@member.id}")
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_email

  end

  def update_email
    respond_to do |format|
      if current_member.update(params.require(:member).permit(:email))
        format.html { redirect_to members_path, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: current_member }
      else
        format.html { render :edit_email }
        format.json { render json: current_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_password

  end

  def update_password
    password_params = params.require(:member).permit(:old_password, :password, :password_confirmation)
    respond_to do |format|
      (current_member.incorrect_old_password = true) unless (current_member.authenticate(params[:old_password]) == false)
      if current_member.update(password_params)
        format.html { redirect_to members_path, notice: 'Password was successfully updated.' }
        format.json { render :show, status: :ok, location: current_member }
      else
        format.html { render :edit_password }
        format.json { render json: current_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def reset_password_edit
    @member = Member.find_by(id: params[:record_hex].to_i(16))
    unless @member.present? && @member.valid_reset_password_token?(params[:reset_token])
      render :invalid_reset_token
    end
  end

  def reset_password_update
    @member = Member.find_by(id: params[:record_hex].to_i(16))
    if @member.present? && @member.valid_reset_password_token?(params[:reset_token])
      @member.password_allow_nil = false
      @member.reset_password_at = nil
      @member.reset_password_digest = nil
      if @member.update(password: params[:password], password_confirmation: params[:password_confirmation])
        redirect_to signin_path
      else
        render :reset_password_edit
      end
    else
      render :invalid_reset_token
    end
  end

  def approve
    @member.accepted = true
    token = @member.generate_reset_password_token!
    MemberMailer.welcome_email(@member, token).deliver_later
    respond_to do |format|
      format.html { redirect_to members_url, notice: "#{@member.full_name} was successfully became a member." }
    end
  end

  def reject
    reason = params[:reason].blank? ? nil :  params[:reason]
    GlobalVar[:last_reject_members_reason] = reason
    @quite_reject = params[:commit] == "Quite Reject"
    if params[:member] == 'all'
      pending_members = Member.unscoped.where(accepted: false)
      unless @quite_reject
        pending_members.pluck(:first_name, :last_name, :email).map { |e| ["#{e[0]} #{e[1]}", e[2]] }.each do |pm|
          MemberMailer.registration_rejected_email(pm[0], pm[1], reason).deliver_later
        end
      end
      pending_members.destroy_all
    else
      if pending_member = Member.unscoped.where(id: params[:member].to_i, accepted: false).take
        pending_member.destroy
        MemberMailer.registration_rejected_email(pending_member.full_name, pending_member.email, reason).deliver_later unless @quite_reject
      end
    end

    respond_to do |format|
      if params[:member] == 'all'
        format.html { redirect_to members_url, notice: "All pending members were successfully#{" and quietly" if @quite_reject} rejected." }
      else

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <%= errors_for @member %>
  <div class="row">
    <div class="input-field col s12 m6">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="input-field col s12 m6">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="input-field col s12 m6">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="input-field col s12 m6">
      <%= f.label :student_number %>
      <%= f.text_field :student_number %>
    </div>

    <div class="input-field col s12 m6">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="input-field col s12 m6">
      <%= select :member, :team_id, [["Choose a team", ""]].concat(Team.all.collect {|t| [ t.name, t.id ] }), { selected: f.object.team_id} %>
      <%= label_tag "member_team_id", 'Team' %>
    </div>

    <div class="col s12">
      <%= f.label :graduated_year %><br>
      <%= radio_button_tag "member[graduated]","0", @member.graduated_year.nil? %>
      <%= label_tag "member_graduated_0","Active" %>
      <%= radio_button_tag "member[graduated]","1", !@member.graduated_year.nil? %>
      <%= f.text_field :graduated_year, for: "member_graduated_1" %>
    </div>
    <div class="row" style="margin-top: 30px">
    <div class="input-field col s6">
      <%= f.check_box :admin %>
      <%= f.label :admin %>
    </div>

    <div class="input-field col s6">
      <%= f.check_box :show_debug_profiler %>
      <%= f.label :show_debug_profiler %>
    </div>

    <div class="input-field col s6">
      <%= f.check_box :accepted %>
      <%= f.label :accepted %>
    </div>
    </div>
    <div class="row" style="margin-top: 30px">
    <% (9..12).each do |i| %>
      <div class="input-field col s6 m3">
        <%= radio_button_tag("member[grade]", i, f.object.grade == i) %>
        <%= label_tag "member[grade][#{i}]", "Grade #{i}" %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="row">
    <div class="actions col s12">
      <%= f.submit class: 'btn', data: { disable_with: nil } %>
      <%= link_to 'Back', members_path, class: 'btn-flat' %>
    </div>
  </div>
<% end %>

app/views/members/_pending_members_table.html.erb
<h3 class="flow-text">Pending Members</h3>
<div class="card-panel" style="padding:10px;">
  <table class="centered except-last" id="pending-members">
    <thead>
      <tr>
        <th>Full Name</th>
        <th class="hide-on-small-only">Grade</th>
        <th class="hide-on-small-only">Old member</th>
        <th class="hide-on-med-and-down">Email</th>
        <th class="hide-on-med-and-down">Student Number</th>
        <th colspan="2"><%= link_to 'Reject All', '#!', class: 'data-modal-trigger', data: { modal_target: "reject_member_modal", modal_fill: {id: 'all', name: "All #{pluralize(members.count,'Pending Member')}"} } %></th>
      </tr>
    </thead>

    <tbody>
      <% members.each do |member| %>
      <tr>
        <td><%= link_to member.full_name, "#m-#{member.id}" %></td>
        <td class="hide-on-small-only"><%= member.grade %></td>
        <td class="hide-on-small-only"><%= member.extra_info["Old member"] if member.extra_info["Old member"] == 'Yes' %></td>
        <td class="hide-on-med-and-down"><%= member.email %></td>
        <td class="hide-on-med-and-down"><%= member.student_number %></td>
        <td><%= link_to 'check', member_approve_path(member), method: :post, class: 'material-icons' %></td>
        <td><%= link_to 'close', '#!', class: 'material-icons data-modal-trigger', data: { modal_target: "reject_member_modal", modal_fill: {id: member.id, name: member.full_name} } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/_quick_members_panel.html.erb
<div class="card-panel hide-on-small-only quick-members-panel">
  <div class="row no-margin-bottom">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a class="active" href="#general_tab_wrap"><i class="tiny material-icons">dashboard</i>General</a></li>
        <li class="tab col s3"><a href="#registration_wrap"><i class="tiny material-icons">assignment</i>Registration</a></li>
      </ul>
    </div>
    <div id="general_tab_wrap" class="col s12 compact-form-wrap center-align">
      <% if member_is_admin? %>
      <p>
        <%= link_to new_member_path, class: "btn-text" do %>
        Create Member
        <% end %>
      </p>
      <% end %>
      <p>
        <%= link_to email_path, class: "btn-text" do %>
        Update my email
        <% end %>
      </p>
      <p>
        <%= link_to password_path, class: "btn-text" do %>
        Update my password
        <% end %>
      </p>
    </div>
    <%= member_is_admin? ? render('registration_menu') : render('registration_info') %>
  </div>
  <div class="preloader-container">
    <%= render "components/spinner", color: "yellow" %>
  </div>
</div>
<div class="quick-links card-panel hide-on-med-and-up">
  <div class="row">
    <%= link_to email_path, class: "btn col s12" do %>
    <i class="material-icons left">person add</i>Update my email
    <% end %>

    <%= link_to password_path, class: "btn col s12" do %>
    <i class="material-icons left">person add</i>Update my password
    <% end %>

    <% if member_is_admin? %>
    <%= link_to new_post_path, class: "btn col s12" do %>
    <i class="material-icons left">person add</i>Create Member
    <% end %>

    <%= link_to new_event_path, class: "btn col s12" do %>
    <i class="material-icons left">assignment</i>Manage Registration Form
    <% end %>
    <% end %>

    <%= link_to register_url, class: "btn col s12" do %>
    <i class="material-icons left">assignment</i>Registration
    <% end %>
  </div>
</div>

app/views/members/_registration_info.html.erb
<div id="registration_wrap" class="col s12 compact-form-wrap">
  <div class="row center-align">
    <% if RegistrationField.valid_member_fields? && RegistrationForm.open? %>
    The Warrior Robotix member registration form is open.<br/>
    <%= link_to register_url, register_url %>
    <% else %>
    The Warrior Robotix member registration form is disabled.
    <%= register_url %>
    <% end %>
  </div>
</div>

app/views/members/_registration_menu.html.erb
<div id="registration_wrap" class="col s12 compact-form-wrap">
  <div class="row">
    <% valid_fields = RegistrationForm.valid_registration_fields? %>
    <div class="col m4 l3 right-align" style="padding-top:1.4rem;">
      <%= render 'registrations/toggle_form', valid_fields: valid_fields %>
    </div>
    <div class="col m8 l9">
      <% if valid_fields %>
        <%= link_to 'Edit Fields', registration_fields_path, class: "btn-text", style: 'margin-top:1rem' %>
        <%= link_to register_url, register_url %>
      <% else %>
        Invalid form: Valid form requires first name, last name, email, grade, and student number fields.
        <br>
        <%= link_to 'Quick FIX', fix_registration_fields_path(), method: :post, class: "btn-text", data: { disable_with: nil } %>
      <% end %>
    </div>
  </div>
</div>

app/views/members/_reject_member_modal.html.erb
<div id="reject_member_modal" class="modal bottom-sheet">
  <div class="container">
    <%= form_tag reject_members_path do %>
    <%= hidden_field_tag 'member', nil, data: {fill: "id"} %>
    <div class="modal-content" style="padding-bottom:0">
      <h4 class="flow-text">Reject <span data-fill="name"></span></h4>
      <div class="row" style="margin-bottom:0">
        <div class="input-field col s12">
          <textarea id="reject_reason" name="reason" class="materialize-textarea" ><%= GlobalVar[:last_reject_members_reason] %></textarea>
          <label for="reject_reason">Reason (Leave blank will reject without reason)</label>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= submit_tag 'Reject', class: "modal-action btn", data: {disable_with: 'Rejecting'} %>
      <%= submit_tag 'Quite Reject', class: "modal-action btn-text", data: {disable_with: 'Rejecting'} %>
      <a href="#!" class="modal-action modal-close btn-flat">Cancel</a>
    </div>
    <% end %>
  </div>
</div>

app/views/members/edit.html.erb
<h1 class="flow-text">Editing Member</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
<%= render 'form' %>
</div>

app/views/members/edit_email.html.erb
<div class="max6">
<h1 class="flow-text">Update Email</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
  <%= form_for(current_member, url: email_path, method: :post) do |f| %>
    <%= errors_for f.object %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="row">
      <div class="actions col s12">
        <%= f.submit 'Update Email', class: 'btn', data: { disable_with: nil } %>
        <%= link_to 'Back', members_path, class: 'btn-flat' %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/members/forgot.html.erb
<div class="max6">
<h1 class="flow-text">Forgot Password</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
<%= form_tag do %>
<div class="row">
  <div class="col s12 input-field">
    <%= label_tag :identifier, "Student Number or Email" %>
    <%= text_field_tag :identifier, params[:identifier] %>
  </div>
  <div class="col s12">
    If you forgot your <strong>student number</strong> and <strong>email</strong>, please contact Warrior Robotix administers
  </div>
</div>

<div class="actions row">
  <button type="submit" name="forgot" class="btn waves-effect waves-light">Send Reset Token</button>
</div>
<% end %>
</div>
</div>

app/views/members/index.html.erb
<% if member_is_admin? %>
<%= hash_modal 'm-', member_path(id: '$') %>
<%= render 'reject_member_modal' %>
<% end %>
<h1 class="flow-text">Members Center</h1>
<%= render 'quick_members_panel'  %>
<% cache(['current_members',@show_attend,@current_members.count,@current_members.maximum(:updated_at)&.utc&.to_s(:nsec),member_is_admin?]) do %>
<%= render('members_table', members: @current_members, title: 'Current Members', show_attend: @show_attend, display_show_attend: member_is_admin?) %>
<% end %>
<% if member_is_admin? %>
<% cache(['pending_members',@pending_members.count,@pending_members.maximum(:updated_at)&.utc&.to_s(:nsec)]) do %>
<%= render('pending_members_table', members: @pending_members, title: 'Pending Members') if @pending_members.present? %>
<% end %>
<% cache(['graduated_members',@graduated_members.count,@graduated_members.maximum(:updated_at)&.utc&.to_s(:nsec)]) do %>
<%= render('members_table', members: @graduated_members, title: 'Graduated Members', show_graduated_year: true) if @graduated_members.present? %>
<% end %>
<% end %>

app/views/members/invalid_reset_token.html.erb
<div class="max6">
<h1 class="flow-text"><%= params[:type].to_s.capitalize %> Password</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
  Your <%= params[:type].to_s %> password URL is invalid. It may causes by following reasons:
  <br/>1. <%= params[:type] == :reset ? 'Reset password' : 'welcome' %> email has sent out more than 2 days ago
  <br/>2. Password has already <%= params[:type] == :reset ? 'reseted' : 'seted' %> by someone
  <br/>
  <br/>
  <%= link_to "Sent a new #{params[:type].to_s} password token", forgot_path %>
</div>
</div>

app/views/members/new.html.erb
<h1 class="flow-text">New Member</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
<%= render 'form' %>
</div>

app/views/members/reset_password_edit.html.erb
<div class="max6">
<h1 class="flow-text"><%= params[:type].to_s.capitalize %> Password</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
<%= form_tag do %>
<%= errors_for @member %>
<div class="row">
  <div class="col s12  input-field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="col s12  input-field">
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation %>
  </div>
</div>
<div class="actions row">
  <button type="submit" name="commit" class="btn waves-effect waves-light"><%= params[:type].to_s.capitalize %></button>
</div>
<% end %>
</div>
</div>

app/views/members/send_reset_token.html.erb
<div class="max6">
<h1 class="flow-text">Forgot Password</h1>
<div class="card-panel" style="padding-bottom:10px;padding-top:10px;">
  <br/>
  A reset password link has sent to your email. If you do not receive any link, your email and student number may not exist in our system. If you are sure your information was correct, please contact Warrior Robotix administers.
  <br/>
  <br/>
</div>
</div>